### ISSUE TITLE
Operation is not valid due to the current state of the object.

### ISSUE THREAD

**Issue by hurui200320** [hurui200320/neo-n3-playground#1]
Running the `info.skyblond.demo.neo.contract.Main`:

```
15:58:57.336 [main] INFO  i.s.demo.neo.utils.ContractHelper - Compiling contract...
15:58:57.404 [main] INFO  i.s.demo.neo.utils.ContractHelper - Deploying contract...
15:59:13.374 [main] INFO  i.s.demo.neo.utils.ContractHelper - Script hash of the deployed contract: 7a9923dbf758baa1161180f67e5eeaca4894b0f6
15:59:13.374 [main] INFO  i.s.demo.neo.utils.ContractHelper - Contract Address: NiQLwtNr2LajqAtUUMQ6EnddhkZYBxmmhG
15:59:13.374 [main] INFO  Application - Start executing user's code
15:59:28.532 [main] INFO  i.s.demo.neo.utils.InvokeHelper - store tx: 992e8bcd3d2f7b511c9b3551e959169d73e9111bc3fbf583a9f1a22e284681a1
15:59:28.534 [main] INFO  i.s.demo.neo.utils.InvokeHelper - store gas fee: 0.0734031
15:59:28.561 [main] ERROR Application - Error occur: 
io.neow3j.transaction.exceptions.TransactionConfigurationException: The vm exited due to the following exception: Operation is not valid due to the current state of the object.
	at io.neow3j.transaction.TransactionBuilder.getSystemFeeForScript(TransactionBuilder.java:397)
	at io.neow3j.transaction.TransactionBuilder.buildTransaction(TransactionBuilder.java:309)
	at io.neow3j.transaction.TransactionBuilder.sign(TransactionBuilder.java:469)
	at info.skyblond.demo.neo.utils.InvokeHelper.buildTxAndSend(InvokeHelper.java:25)
	at info.skyblond.demo.neo.utils.InvokeHelper.invokeFunction(InvokeHelper.java:31)
	at info.skyblond.demo.neo.Main.testRun(Main.java:32)
	at info.skyblond.demo.neo.Main.main(Main.java:53)
15:59:28.561 [main] INFO  Application - Trying to cleaning up...
15:59:28.561 [main] INFO  i.s.demo.neo.utils.ContractHelper - Destroying contract...
15:59:43.717 [main] INFO  i.s.demo.neo.utils.InvokeHelper - destroy tx: 7961578c40d6bf5148644596599377f48bfa5758589dba96d4c28efe58553129
15:59:43.717 [main] INFO  i.s.demo.neo.utils.InvokeHelper - destroy gas fee: 0.0413274
```

Error `Operation is not valid due to the current state of the object.` is caused by the code below:
```
StdLib.jsonSerialize(hash160.asByteString().toInteger());
```

The code: `hash160.asByteString().toInteger()` alone is nothing wrong, but passing it to `StdLib.jsonSerialize` will cause the error, as long as the object passing to `StdLib.jsonSerialize` related with(executed) this `.asByteString().toInteger()` thing.

**The code is in branch [`issue/1`](https://github.com/hurui200320/neo-n3-playground/tree/issue/1)**

**Comment by hurui200320** [comment]
Detailed explanation for codes:

`SomeObject` class shows the error will occur no matter you invoke the statement directly, or warp it into some function:

https://github.com/hurui200320/neo-n3-playground/blob/ab3524737098ab7859b8a7da950a2401144cb332/src/main/java/info/skyblond/demo/neo/contract/TestContract.java#L17-L27

Line 24 use the statement `.asByteString().toInteger()`, then throw it into `StdLib.jsonSerialize` at line 37:

https://github.com/hurui200320/neo-n3-playground/blob/ab3524737098ab7859b8a7da950a2401144cb332/src/main/java/info/skyblond/demo/neo/contract/TestContract.java#L34-L39

This also cause the error as same as line 38.

However, the statement itself is nothing wrong:

https://github.com/hurui200320/neo-n3-playground/blob/ab3524737098ab7859b8a7da950a2401144cb332/src/main/java/info/skyblond/demo/neo/contract/TestContract.java#L41-L46

The bar function use the data directly without throwing it into `StdLib.jsonSerialize` , and everything works ok.

You can switch the function by comment line 33 and uncomment line 34:

https://github.com/hurui200320/neo-n3-playground/blob/ab3524737098ab7859b8a7da950a2401144cb332/src/main/java/info/skyblond/demo/neo/Main.java#L24-L43

Invoking bar gives this log:
```
16:10:25.157 [main] INFO  i.s.demo.neo.utils.ContractHelper - Compiling contract...
16:10:25.229 [main] INFO  i.s.demo.neo.utils.ContractHelper - Deploying contract...
16:10:41.223 [main] INFO  i.s.demo.neo.utils.ContractHelper - Script hash of the deployed contract: 511e1d4c1028a2a6e6b960e2a69598dc578bfe2f
16:10:41.223 [main] INFO  i.s.demo.neo.utils.ContractHelper - Contract Address: NQHjspYwMadjEpzEhwY1qaKnDgCnpsEayE
16:10:41.223 [main] INFO  Application - Start executing user's code
16:10:56.378 [main] INFO  i.s.demo.neo.utils.InvokeHelper - store tx: 2bb9ba1afb9dd964ee94eef28807f879edb15fa5834e0e674152b75b4148a91b
16:10:56.379 [main] INFO  i.s.demo.neo.utils.InvokeHelper - store gas fee: 0.0734031
16:11:11.525 [main] INFO  i.s.demo.neo.utils.InvokeHelper - bar tx: 97d8650705927e716d97a3035c9505c22b823d98f2b9fdf6b1391c05cb5ab3fe
16:11:11.526 [main] INFO  i.s.demo.neo.utils.InvokeHelper - bar gas fee: 0.0539543
16:11:11.526 [main] INFO  Application - Execution result: 423635860769272551031687064804440294377881385694
16:11:11.526 [main] INFO  Application - Expected result : 4a347d2ed99c633396aac231dde0130bab48bade
16:11:11.526 [main] INFO  i.s.demo.neo.utils.ContractHelper - Destroying contract...
16:11:26.684 [main] INFO  i.s.demo.neo.utils.InvokeHelper - destroy tx: 9b7664f847cc9cef0a7175b045b58f3eb0d7b24cdb154612b25aff78adff9196
16:11:26.685 [main] INFO  i.s.demo.neo.utils.InvokeHelper - destroy gas fee: 0.0413274
```
I guess `0x4a347d2ed99c633396aac231dde0130bab48bade` end with `0xe`, i.e. 14, so the I guess that big number ending with 4 is correct result. Anyway, this doesn't throw any error.

**Comment by hurui200320** [comment]
> I found out that this issue is based on a limitation of the `StdLib` contract. integers are restricted to the range (-2^53, 2^53). A Hash160 is, as its name says 160 bit long, thus, if we interpret it as an unsigned integer it can have values of up to 2^160-1. With a high probability it will be higher than 2^53-1 and thus over the limit set in the StdLib contract. 
> I will ask the core team why this restriction is in place.
> For now, you cannot use Hash160 integers for json deserialization.
> I recommend using `StdLib.base64Encode(hash160.toByteString())` before you `jsonSerialize` the hash, otherwise the NeoVM will try to interpret the hash160 as a UTF-8 string.
> (from Claude Muller)
