### ISSUE TITLE
`Invalid type for PICKITEM: Any` & `RVCount doesn't match with EvaluationStack`

### ISSUE THREAD

**Issue by hurui200320** [hurui200320/neo-n3-playground#2]
This issue is discovered when I was trying to count a list using for loop. The `list.get(index)` statement is in the loop so I originally thought it was the statement in the loop cause the error, since the `get(index)` wraps the instruction `PICKITEM`. But today I'm trying to reproduce this bug, and notice that the for loop itself can trigger the error:

https://github.com/hurui200320/neo-n3-playground/blob/c070dbf78b89cf22d2d926819db8a3419a942f70/src/main/java/info/skyblond/demo/neo/contract/TestContract.java#L17-L26

Any of those for loop can trigger the error. More detailed speaking, there are two different errors are triggered:
`for (int i = 9; i < 0; i++);` and `for (int i = 0; i < 9; i++);` triggered `RVCount doesn't match with EvaluationStack`.
`for (int i = 0; i < this.list.size(); i++);` triggered `Invalid type for PICKITEM: Any`.

However if those loops are in the contract as a static function, then nothing goes wrong, the error is triggered only if they are in a object:

https://github.com/hurui200320/neo-n3-playground/blob/c070dbf78b89cf22d2d926819db8a3419a942f70/src/main/java/info/skyblond/demo/neo/contract/TestContract.java#L37-L47

Runtime log is here:
```
15:41:55.055 [main] INFO  i.s.demo.neo.utils.ContractHelper - Compiling contract...
15:41:55.119 [main] INFO  i.s.demo.neo.utils.ContractHelper - Deploying contract...
15:42:11.804 [main] INFO  i.s.demo.neo.utils.ContractHelper - Script hash of the deployed contract: 0fd607bc6c7552addfa8f7ef8c1251b567fde403
15:42:11.804 [main] INFO  i.s.demo.neo.utils.ContractHelper - Contract Address: NLGZXpsG5CN5a7HtEhGLXqCsFN93oT4tog
15:42:11.804 [main] INFO  Application - Start executing user's code
15:42:26.958 [main] INFO  i.s.demo.neo.utils.InvokeHelper - init tx: 29540c60674f0116a8815b3b35e2ac86b67431d203d3589dfd5521d845a9700d
15:42:26.959 [main] INFO  i.s.demo.neo.utils.InvokeHelper - init gas fee: 0.0717808
15:42:26.985 [main] ERROR Application - Error occur: 
io.neow3j.transaction.exceptions.TransactionConfigurationException: The vm exited due to the following exception: RVCount doesn't match with EvaluationStack
	at io.neow3j.transaction.TransactionBuilder.getSystemFeeForScript(TransactionBuilder.java:397)
	at io.neow3j.transaction.TransactionBuilder.buildTransaction(TransactionBuilder.java:309)
	at io.neow3j.transaction.TransactionBuilder.sign(TransactionBuilder.java:469)
	at info.skyblond.demo.neo.utils.InvokeHelper.buildTxAndSend(InvokeHelper.java:25)
	at info.skyblond.demo.neo.utils.InvokeHelper.invokeFunction(InvokeHelper.java:31)
	at info.skyblond.demo.neo.Main.testRun(Main.java:32)
	at info.skyblond.demo.neo.Main.main(Main.java:53)
15:42:26.985 [main] INFO  Application - Trying to cleaning up...
15:42:26.985 [main] INFO  i.s.demo.neo.utils.ContractHelper - Destroying contract...
15:42:45.000 [main] INFO  i.s.demo.neo.utils.InvokeHelper - destroy tx: 139f720f49ca0e9793dfb01f81cfbc90a851a88c4dca4230dca61bae49914809
15:42:45.001 [main] INFO  i.s.demo.neo.utils.InvokeHelper - destroy gas fee: 0.0413274
```

Using Neow3j 3.10.0
Code is in branch [`issue/2`](https://github.com/hurui200320/neo-n3-playground/tree/issue/2)

**Comment by hurui200320** [comment]
Fixed at 3.11.2
