### ISSUE TITLE
Replacing contract owner address by operating Java Bytecode.

### ISSUE THREAD

**Issue by hurui200320** [hurui200320/neo-n3-playground#3]
Last week when I was trying to deploy the contract to the RC4 test net, I forgot to change the contract owner address from the neo express one to the real one. Luckily that is test net.

The contract owner address is a  static field in the contract. Currently, I have no idea how to manage it. I came up with writing the contract owner address into the storage area on deployment, and the value depends on the network magic number, then read it when is needed. But that is not the most elegant way.

Today I came up with another idea by using a placeholder in the code and replace it with the real address on demand before compiling. The placeholder needs to be a unique string literal and must not be a valid address. By doing so, we achieved the following goals:

+ If we forget to set the owner address, the compiler will give an error since the placeholder cannot be translated into Hash160.
+ We can use the same code in the develop and master branch without changing it to private network setup in develop branch and change it back in the master branch.
+ It's handy when we need to fill CatToken address in WCAContract. When we changed the CatToken, we must fail the test at least once to get the CatToken address, but now we can deploy the CatToken and fill the address into WCAContract on the fly.

**Comment by hurui200320** [comment]
After digging around with Google, Now I can do it with ASM's Visitor API. Here is the result:

This is the test contract, where `CONTRACT_OWNER` is generated from `<CONTRACT_OWNER_HASH_PLACEHOLDER>`. 

https://github.com/hurui200320/neo-n3-playground/blob/932a8ab71172747c02290c3602254809d1c2e9d4/src/main/java/info/skyblond/demo/neo/contract/TestContract.java#L17-L24

This is not a valid Neo N3 address, so it will give an error when compiling the contract:

```
io.neow3j.compiler.CompilerException: TestContract.java: 19: error:
Invalid address '<CONTRACT_OWNER_HASH_PLACEHOLDER>' used in static field initialization.
	at io.neow3j.compiler.converters.MethodsConverter.handleStringLiteralsConverter(MethodsConverter.java:241)
	at io.neow3j.compiler.converters.MethodsConverter.handleInvoke(MethodsConverter.java:140)
	at io.neow3j.compiler.converters.MethodsConverter.convert(MethodsConverter.java:79)
	at io.neow3j.compiler.Compiler.handleInsn(Compiler.java:438)
	at io.neow3j.compiler.InitsslotNeoMethod.convert(InitsslotNeoMethod.java:55)
	at io.neow3j.compiler.Compiler.compile(Compiler.java:279)
	at io.neow3j.compiler.Compiler.compile(Compiler.java:257)
	at info.skyblond.demo.neo.utils.ContractHelper.compileContract(ContractHelper.java:34)
	at info.skyblond.demo.neo.Main.main(Main.java:53)
```

However, I replaced the placeholder with a valid address before compiling:

https://github.com/hurui200320/neo-n3-playground/blob/932a8ab71172747c02290c3602254809d1c2e9d4/src/main/java/info/skyblond/demo/neo/Main.java#L49-L55

Then deploy and invoke the contract:

https://github.com/hurui200320/neo-n3-playground/blob/932a8ab71172747c02290c3602254809d1c2e9d4/src/main/java/info/skyblond/demo/neo/Main.java#L32-L42

The log is here:

```
15:32:22.078 [main] INFO  Application - Returned address: NR9pwfToFHHYti4RY1dLP3wGr4waSGn7NH
```

You can see the result is `NR9pwfToFHHYti4RY1dLP3wGr4waSGn7NH`, aka the address we replaced.

This is a straightforward demo, and I intend to integrate this code into the unit test of [NekoHitDev/Ritmin](https://github.com/NekoHitDev/Ritmin), so we can deploy and test it with different owner addresses without changing it manually. (Since last time I accidentally deployed the developing code to the public test network, which owner address is defined publicly in the neo express's config file.)

**Comment by hurui200320** [comment]
Here is the Java Bytecode of `TestContract.class`:

```
// class version 52.0 (52)
// access flags 0x21
public class info/skyblond/demo/neo/contract/TestContract {

  // compiled from: TestContract.java

  @Lio/neow3j/devpack/annotations/ManifestExtra$ManifestExtras;(value={@Lio/neow3j/devpack/annotations/ManifestExtra;(key="name", value="Test Contract"), @Lio/neow3j/devpack/annotations/ManifestExtra;(key="github", value="https://github.com/hurui200320/neo-n3-playground"), @Lio/neow3j/devpack/annotations/ManifestExtra;(key="author", value="hurui200320")}) // invisible

  @Lio/neow3j/devpack/annotations/Permission;(contract="*") // invisible

  @Lio/neow3j/devpack/annotations/Trust;(value="*") // invisible
  // access flags 0x2609
  public static abstract INNERCLASS io/neow3j/devpack/annotations/ManifestExtra$ManifestExtras io/neow3j/devpack/annotations/ManifestExtra ManifestExtras

  // access flags 0x8
  static Lio/neow3j/devpack/Hash160; CONTRACT_OWNER

  // ......

  // access flags 0x8
  static <clinit>()V
   L0
    LINENUMBER 19 L0
    LDC "<CONTRACT_OWNER_HASH_PLACEHOLDER>"
    INVOKESTATIC io/neow3j/devpack/StringLiteralHelper.addressToScriptHash (Ljava/lang/String;)Lio/neow3j/devpack/Hash160;
    PUTSTATIC info/skyblond/demo/neo/contract/TestContract.CONTRACT_OWNER : Lio/neow3j/devpack/Hash160;
    RETURN
    MAXSTACK = 1
    MAXLOCALS = 0
}
```

We can see the `CONTRACT_HASH` field is initialized when initializing the class, aka the `<clinit>` method. It loads the constant string and invokes the native method offered by neow3j's compiler to translate the string into Hash160.

So our goal is to replace that placeholder with our real address by ASM, then feed the result into neow3j's compiler.

To do that, we need a `ClassVisitor` since we are using the visitor API:

https://github.com/hurui200320/neo-n3-playground/blob/932a8ab71172747c02290c3602254809d1c2e9d4/src/main/java/info/skyblond/demo/neo/compile/ReplaceClassVisitor.java#L10-L36

It takes a map as a parameter, telling the code what to replace. We override the `visitMethod` method. Since we want to mess around with `<clinit>`, we check the name of each method and only do the replacement for `<clinit>`. To replace, line 21 to 33 shows that we override the LDC instruction and replace the target value.


To apply that replace, we need some utils code:

https://github.com/hurui200320/neo-n3-playground/blob/932a8ab71172747c02290c3602254809d1c2e9d4/src/main/java/info/skyblond/demo/neo/compile/CompileUtils.java#L10-L16

It rewrites the source class and returns a byte array, which is the modified class file. Then we can supply it to neow3j's compiler as an `InputStream`:

https://github.com/hurui200320/neo-n3-playground/blob/932a8ab71172747c02290c3602254809d1c2e9d4/src/main/java/info/skyblond/demo/neo/utils/ContractHelper.java#L30-L34

**Comment by hurui200320** [comment]
If we're using Tree API, then code will be more cleaner. We just need to replace the `getModifiedClass` in class `CompileUtils.java`:

```Java
    public static byte[] getModifiedClass(String canonicalClassName, Map<String, String> replaceMap) throws IOException {
        ClassReader reader = new ClassReader(canonicalClassName);
        ClassNode classNode = new ClassNode();
        reader.accept(classNode, ClassReader.EXPAND_FRAMES);

        for (MethodNode methodNode : classNode.methods) {
            if (methodNode.name.equals("<clinit>")) {
                for (AbstractInsnNode insnNode : methodNode.instructions) {
                    if (insnNode.getType() == AbstractInsnNode.LDC_INSN) {
                        LdcInsnNode node = (LdcInsnNode) insnNode;
                        if (node.cst instanceof String && replaceMap.containsKey(node.cst)) {
                            node.cst = replaceMap.get(node.cst);
                            break;
                        }
                    }
                }
                break;
            }
        }

        ClassWriter writer = new ClassWriter(ClassWriter.COMPUTE_MAXS);
        classNode.accept(writer);
        return writer.toByteArray();
    }
```

That's all. You don't need a visitor anymore. Also, since neow3j uses Tree API, it will be easier to integrate this than the visitor API.
